name: Weblets Docker Build/Push
on:
  push:
    branches:
      - development
    paths:
      - "packages/weblets/**"
  release:
    types: [published]

jobs:
  Build-and-push-docker-image:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=6144"

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2

      - name: Args in case development
        if: ${{ github.ref == 'refs/heads/development' }}
        run: |
          VERSION=$GITHUB_SHA
          echo VERSION=${VERSION:0:7} >> $GITHUB_ENV

      - name: Args in case test
        if: |
          github.event_name == 'release'
        run: |
          VERSION=$GITHUB_REF 
          echo VERSION=${VERSION:10:12} >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: packages/weblets
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/grid_weblets:${{env.VERSION}}
          build-args: |
            VERSION=${{env.VERSION}}
